name: iconoir_flutter
description: Flutter library for Iconoir, the biggest open source icon library with tons of free icons.
version: 7.0.1
homepage: https://iconoir.com
repository: https://github.com/iconoir-icons/iconoir
funding:
  - https://opencollective.com/iconoir

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
