name: iconoir_flutter
description: Flutter library for Iconoir icon set
version: 6.11.0
homepage: https://iconoir.com
repository: https://github.com/lucaburgio/iconoir.git
issue_tracker: https://github.com/lucaburgio/iconoir/issues

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - ../../icons/
